dependencies {
    api(project(":loader"))
    compileOnly("net.bytebuddy:byte-buddy:1.14.14")
    compileOnly("dev.dejvokep:boosted-yaml:1.3.4")
    compileOnly("net.kyori:adventure-api:4.16.0")
    compileOnly("net.kyori:adventure-text-minimessage:4.16.0")
    compileOnly("net.kyori:adventure-text-serializer-legacy:4.16.0")
    compileOnly("net.kyori:adventure-text-serializer-gson:4.16.0")
    compileOnly("org.jetbrains:annotations:24.0.0")
    compileOnly("org.slf4j:slf4j-api:2.0.13")
    compileOnly("org.apache.logging.log4j:log4j-core:2.23.1")
    compileOnly("com.google.code.gson:gson:2.10.1")
    compileOnly("org.incendo:cloud-core:2.0.0-beta.5")
    compileOnly("org.incendo:cloud-minecraft-extras:2.0.0-beta.6")
}